# Generated by Django 5.0.6 on 2024-06-19 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustiveis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='bomba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to='combustiveis.bomba'),
        ),
        migrations.AlterField(
            model_name='bomba',
            name='tanque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bombas', to='combustiveis.tanque'),
        ),
    ]
